### ISSUE TITLE
[cloud模块]eureka控制台支持手动移除某个服务的实例？

### ISSUE THREAD

**Issue by wayshall** [wayshall/onetwo#17]
eureka控制台支持手动移除某个服务的实例，某些部署情况需要。

**Comment by wayshall** [comment]
需要如下配置：
```yaml
eureka:
    dashboard: 
        baseurl: /gateway/eureka
        enabled: false
```
