### ISSUE TITLE
增加异常映射配置

### ISSUE THREAD

**Issue by wayshall** [wayshall/onetwo#30]
增加异常映射配置，可以更灵活定制各种异常

**Comment by wayshall** [comment]
增加了下面的配置支持：

```yaml
jfish.mvc.exceptionsMapping:
    exceptionName:
        code: test
        message: 测试
```
