### ISSUE TITLE
[boot模块] 增加websocket和stomp集成？

### ISSUE THREAD

**Issue by wayshall** [wayshall/onetwo#46]
如题

**Comment by wayshall** [comment]
1、添加spring boot websocket依赖
2、在yaml文件增加如下配置：
```yaml
jfish:
  websocket: 
    enabled: true
    stomp:
      endpoints: /stomp
      allowedOrigins: '*'
    broker:
      simplePrefixes: /broadcast
      appPrefixes: /app
      userPrefix: /user
```
