### ISSUE TITLE
增加过滤器防止http host头攻击

### ISSUE THREAD

**Issue by wayshall** [wayshall/onetwo#87]
增加过滤器防止http host头攻击

**Comment by wayshall** [comment]
配置：
```yaml
jfish:
    hostfilter:
        allowIps: xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx:8080
```
